version: '3.8'

services:
  app:
    build: .
    ports:
      - '8889:3000'
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: yqq
      DB_PASSWORD: 1989315788
      DB_DATABASE: home
      REDIS_HOST: redis 
      REDIS_PORT: 6379
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: mysql:8.4.0
    environment:
      MYSQL_ROOT_PASSWORD: 1989315788
      MYSQL_DATABASE: home 
      MYSQL_USER: yqq 
      MYSQL_PASSWORD: 1989315788
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s 
      timeout: 3s 
      retries: 10
    ports:
      - '3306:3306'

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
      
volumes:
  mysql_data:
  redis_data: