version: "3.8"

services:
  app:
    build: .
    ports:
      - "8889:3000" # 宿主机8889 -> 容器3000
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1989315788
      DB_DATABASE: users
    restart: unless-stopped

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1989315788
      MYSQL_DATABASE: users
      MYSQL_USER: root
      MYSQL_PASSWORD: 1989315788
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "3306:3306"

volumes:
  mysql_data:
